package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/radovskyb/watcher"
)

// generateRoutes scraps handler dir and generates Typescipt types
func generateRoutes(handlerDir, outputPath string) {
	routes, err := scrapeRoutes(handlerDir)
	if err != nil {
		fmt.Printf("\033[1;31m  ✘ Error scraping routes:\033[0m %v\n", err)
		return
	}

	err = writeTSFile(outputPath, routes)
	if err != nil {
		fmt.Printf("\033[1;31m  ✘ Error writing file:\033[0m %v\n", err)
		return
	}

	fmt.Printf("\033[1;32m  ✔ Generated\033[0m  \033[1m%d routes\033[0m \033[2mto %s\033[0m\n", len(routes), filepath.Base(outputPath))
}

func startWatcher(handlerDir, outputPath string) {
	w := watcher.New()

	w.FilterOps(watcher.Write, watcher.Create, watcher.Remove, watcher.Rename)

	r := regexp.MustCompile(`\.go$`)
	w.AddFilterHook(watcher.RegexFilterHook(r, false))

	fmt.Println("\033[1;36m" + `
   ___  ____  __  ____________   _________   __
  / _ \/ __ \/ / / /_  __/ __/  / ___/ __/__/ /
 / , _/ /_/ / /_/ / / / / _/   / (_ / _// _  /
/_/|_|\____/\____/ /_/ /___/   \___/___/\_,_/
	` + "\033[0m")

	fmt.Printf("\033[1m  Target \033[0m \033[36m➜\033[0m \033[2m%s\033[0m\n", handlerDir)
	fmt.Printf("\033[1m  Output \033[0m \033[36m➜\033[0m \033[2m%s\033[0m\n", outputPath)
	fmt.Println("\033[2m  Watching for changes...\033[0m")

	go func() {
		for {
			select {
			case event := <-w.Event:

				fmt.Printf("\033[1;33m  • \033[0m\033[1mChange detected\033[0m  \033[2m%s\033[0m\n", event.Name())
				generateRoutes(handlerDir, outputPath)
			case err := <-w.Error:
				log.Fatalln(err)
			case <-w.Closed:
				return
			}
		}
	}()

	if err := w.AddRecursive(handlerDir); err != nil {
		log.Fatalf("Failed to watch directory: %v\n", err)
	}

	if err := w.Start(time.Millisecond * 500); err != nil {
		log.Fatalln(err)
	}
}

// scrapeRoutes walks through the directory and parses every .go file
func scrapeRoutes(dir string) (map[string]string, error) {
	routes := make(map[string]string)
	fset := token.NewFileSet()

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {

		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}

		node, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil
		}

		ast.Inspect(node, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || (sel.Sel.Name != "Handle" && sel.Sel.Name != "HandleFunc") {
				return true
			}

			if len(call.Args) > 0 {
				if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
					rawRoute := strings.Trim(lit.Value, "\"")
					parts := strings.Split(rawRoute, " ")
					if len(parts) == 2 {
						method := parts[0]
						pathUrl := parts[1]

						key := strings.ReplaceAll(pathUrl, "/", "_")
						key = strings.ReplaceAll(key, "-", "_")
						key = strings.ReplaceAll(key, "{", "")
						key = strings.ReplaceAll(key, "}", "")
						fullKey := fmt.Sprintf("%s_%s", method, strings.ToUpper(strings.Trim(key, "_")))

						routes[fullKey] = rawRoute
					}
				}
			}
			return true
		})
		return nil
	})

	return routes, err
}

// writeTSFile formats the map into the final TypeScript content
func writeTSFile(outputPath string, routes map[string]string) error {
	var sb strings.Builder
	sb.WriteString("// This file is auto-generated by the Go route scraper. DO NOT EDIT.\n")
	sb.WriteString("export const API_ROUTES = {\n")

	sortedKeys := getSortedKeys(routes)

	for _, k := range sortedKeys {
		fmt.Fprintf(&sb, "  %s: \"%s\",\n", k, routes[k])
	}

	sb.WriteString("} as const;\n")

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}

var methodOrder = map[string]int{
	"GET":    1,
	"POST":   2,
	"PATCH":  3,
	"PUT":    4,
	"DELETE": 5,
}

func getSortedKeys(r map[string]string) []string {

	keys := make([]string, 0, len(r))
	for k := range r {
		keys = append(keys, k)
	}

	sort.Slice(keys, func(i, j int) bool {

		valI, valJ := r[keys[i]], r[keys[j]]

		partsI := strings.Fields(valI)
		partsJ := strings.Fields(valJ)

		pathI := partsI[1]
		pathJ := partsJ[1]

		if pathI != pathJ {

			return pathI < pathJ
		}

		methodI := strings.Split(keys[i], "_")[0]
		methodJ := strings.Split(keys[j], "_")[0]

		return methodOrder[methodI] < methodOrder[methodJ]
	})

	return keys
}
